id: P006722
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1PD159378
  title: དཔལ་ཡུལ་བའི་མཁས་གྲུབ་འགའི་མཛད་རྣམ་ལྷན་བསྡུས།
  author: ''
  volumes:
    459e6915989141779312986b64c5fc91:
      image_group_id: I2PD18995
      title: ''
      volume_number: 1
      total_pages: 448
      base_file: v001.txt
